feat: add arm64 build
Azure/aad-pod-identity pull request #950
Opened 2021-01-26 06:06 UTC by aramase

**Reason for Change**:

**Requirements**

- [x] squashed commits
- [x] included documentation
- [x] added unit tests and e2e tests (if applicable). See [test standard](https://github.com/Azure/aad-pod-identity/blob/master/CONTRIBUTING.md#test-standard) for more details.
- [x] ran `make precommit`

**Issue Fixed**:

fixes #931 

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

- [ ] yes
- [x] no

**Notes for Reviewers**:

2021-01-26 06:06 UTC, aramase commented
```json
➜ docker manifest inspect aramase/mic:arch03
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:a4bdd3e8e97d4a3fc9b8ed8bb3d2ff0b2cda534f8635e1cde823c3bad60a76d6",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 737,
         "digest": "sha256:733f288f543716d0f665028ca24d022e2a8c2cb1d6b41dd4d950ce953317ce56",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 737,
         "digest": "sha256:eee4cca84ed8b794f1e1165be28ef639f8de141de2c32666b6806653946b71c9",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      }
   ]
}
```

2021-01-27 20:39 UTC, chewong requested changes

2021-01-27 20:39 UTC, chewong commented on Makefile
> +	fi
`DOCKER_CLI_EXPERIMENTAL` is already exported above

```suggestion
	if ! docker buildx ls | grep -q container-builder; then \
		docker buildx create --name container-builder --use; \
	fi
```

2021-01-27 20:39 UTC, chewong commented on Makefile
> +DOCKER_CLI_EXPERIMENTAL=enabled
nit:
```suggestion
DOCKER_CLI_EXPERIMENTAL = enabled
```

2021-01-27 20:39 UTC, chewong commented on Dockerfile
> +    GOARM=$(echo ${TARGETPLATFORM} | cut -d / -f3); export GOARM=${GOARM:1} && \
GOARM only accepts 5, 6, or 7 according to https://github.com/golang/go/wiki/GoArm

```suggestion
     export GOARM=$(echo ${TARGETPLATFORM} | cut -d / -f3 | tr -d 'v') && \
```

2021-01-27 23:25 UTC, chewong approved these changes

2021-01-28 00:33 UTC, merged